[theme]
base = "dark"
primaryColor = "#EC0016"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#111827"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
